const generalTypes = {
  ENABLE_LOADING: "ENABLE_LOADING",
  DISABLE_LOADING: "DISABLE_LOADING",
  UPDATE_SUCCESS_NOTIFICATION: "UPDATE_SUCESS_NOTIFICATION",
  UPDATE_INFORMATION_NOTIFICATION: "UPDATE_INFORMATION_NOTIFICATION",
  CLEAR_NOTIFICATION: "CLEAR_NOTIFICATION",
  UPDATE_FAIL_NOTIFICATION: "UPDATE_FAIL_NOTIFICATION",
  UPDATE_SUCCESS_API_REQUEST: "UPDATE_SUCCESS_API_REQUEST",
  UPDATE_FAIL_API_REQUEST: "UPDATE_FAIL_API_REQUEST",
  CLEAR_API_REQUEST: "CLEAR_API_REQUEST",
  SAVE_LAST_ENDPOINT: "SAVE_LAST_ENDPOINT",
  REMOVE_LAST_ENDPOINT: "REMOVE_LAST_ENDPOINT",
  UPDATE_LANG: "UPDATE_LANG"
};

export interface GeneralState {
  lang: string
}

export default generalTypes;
