export enum PERMISSIONS {
  FO_MAIN_CAMPAIGN_ACCESS = 'ads_FO_main_campaign_access',
  FO_SPONSORED_PRODUCTS_ACCESS = 'ads_FO_sponsored_products_access',
  FO_SPONSORED_BRANDS_ACCESS = 'ads_FO_sponsored_brands',
  FO_OFFLINE_ADVERTISING_ACCESS = 'ads_FO_offline_advertising_access',
  FO_INSIGHTS_ACCESS = 'ads_FO_insights_access',
  FO_TOPUP_ACCESS = 'ads_FO_topup_access',
  FO_FINANCE_ACCESS = 'ads_FO_finance_access',
  BO_MAIN_CAMPAIGN_ACCESS = 'ads_BO_main_campaign_access',
  BO_PACKAGES_ACCESS = 'ads_BO_packages_access',
  BO_USER_MANAGEMENT_ACCESS = 'ads_BO_user_management_access',
  BO_SPONSORED_PRODUCTS_ACCESS = 'ads_BO_sponsored_products_access',
  BO_SPONSORED_BRANDS_ACCESS = 'ads_BO_sponsored_brands',
  BO_OFFLINE_ADVERTISING_ACCESS = 'ads_BO_offline_advertising_access',
  BO_INSIGHTS_ACCESS = 'ads_BO_insights_access',
  FO_TIER1_EVENTS_ACCESS = 'ads_FO_tier1_events',
  BO_TIER1_EVENTS_ACCESS = 'ads_BO_tier1_events',
  BO_SETTINGS_ACCESS = 'ads_BO_user_management_access',
}

// this roles will be used  to decide which UI will be visible to user
// TODO: replace this with user_type that will be coming from backend
// TODO rename to singular to follow enum names
export enum ROLES {
  VENDOR = 'vendor',
  ADMIN = 'admin',
  GURU = 'guru',
}

export const getPermissions = {
  vendor: [
    PERMISSIONS.FO_MAIN_CAMPAIGN_ACCESS,
    PERMISSIONS.FO_OFFLINE_ADVERTISING_ACCESS,
    PERMISSIONS.FO_INSIGHTS_ACCESS,
    PERMISSIONS.FO_SPONSORED_PRODUCTS_ACCESS,
    PERMISSIONS.FO_SPONSORED_BRANDS_ACCESS,
    PERMISSIONS.FO_FINANCE_ACCESS,
    PERMISSIONS.FO_TOPUP_ACCESS,
    PERMISSIONS.FO_TIER1_EVENTS_ACCESS,
  ],
  admin: [
    PERMISSIONS.BO_MAIN_CAMPAIGN_ACCESS,
    PERMISSIONS.BO_PACKAGES_ACCESS,
    PERMISSIONS.BO_USER_MANAGEMENT_ACCESS,
    PERMISSIONS.BO_SPONSORED_PRODUCTS_ACCESS,
    PERMISSIONS.BO_SPONSORED_BRANDS_ACCESS,
    PERMISSIONS.BO_OFFLINE_ADVERTISING_ACCESS,
    PERMISSIONS.BO_INSIGHTS_ACCESS,
    PERMISSIONS.BO_TIER1_EVENTS_ACCESS,
  ],
  guru: [
    PERMISSIONS.FO_MAIN_CAMPAIGN_ACCESS,
    PERMISSIONS.FO_OFFLINE_ADVERTISING_ACCESS,
    PERMISSIONS.FO_INSIGHTS_ACCESS,
    PERMISSIONS.FO_SPONSORED_PRODUCTS_ACCESS,
    PERMISSIONS.FO_SPONSORED_BRANDS_ACCESS,
    PERMISSIONS.FO_FINANCE_ACCESS,
    PERMISSIONS.FO_TOPUP_ACCESS,
    PERMISSIONS.FO_TIER1_EVENTS_ACCESS,
    PERMISSIONS.BO_MAIN_CAMPAIGN_ACCESS,
    PERMISSIONS.BO_PACKAGES_ACCESS,
    PERMISSIONS.BO_USER_MANAGEMENT_ACCESS,
    PERMISSIONS.BO_SPONSORED_PRODUCTS_ACCESS,
    PERMISSIONS.BO_SPONSORED_BRANDS_ACCESS,
    PERMISSIONS.BO_OFFLINE_ADVERTISING_ACCESS,
    PERMISSIONS.BO_INSIGHTS_ACCESS,
    PERMISSIONS.BO_TIER1_EVENTS_ACCESS,
  ],
}
